//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViPKS_PR10_FirstTry.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillOfMaterials
    {
        public long Id { get; set; }
        public long SpecificationId { get; set; }
        public long MaterialId { get; set; }
        public float Quantity { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Specification Specification { get; set; }
    }
}
