//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViPKS_PR10_FirstTry.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BillOfMaterials> BillOfMaterials { get; set; }
        public DbSet<Client> Client { get; set; }
        public DbSet<Department> Department { get; set; }
        public DbSet<Employee> Employee { get; set; }
        public DbSet<EmployeePosition> EmployeePosition { get; set; }
        public DbSet<Equipment> Equipment { get; set; }
        public DbSet<EquipmentStatus> EquipmentStatus { get; set; }
        public DbSet<Material> Material { get; set; }
        public DbSet<MaterialRemains> MaterialRemains { get; set; }
        public DbSet<Order> Order { get; set; }
        public DbSet<OrderAssignment> OrderAssignment { get; set; }
        public DbSet<OrderStatus> OrderStatus { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<ProductionOrder> ProductionOrder { get; set; }
        public DbSet<Purchase> Purchase { get; set; }
        public DbSet<Specification> Specification { get; set; }
        public DbSet<Supplier> Supplier { get; set; }
        public DbSet<SupplierPurchase> SupplierPurchase { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<UnitOfMeasurement> UnitOfMeasurement { get; set; }
    }
}
