//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViPKS_PR10_FirstTry.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.OrderAssignment = new HashSet<OrderAssignment>();
        }
    
        public long Id { get; set; }
        public long EmployeePositionId { get; set; }
        public long DepartmentId { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public float SalaryRate { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual EmployeePosition EmployeePosition { get; set; }
        public virtual ICollection<OrderAssignment> OrderAssignment { get; set; }
    }
}
