//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViPKS_PR10_FirstTry.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public Equipment()
        {
            this.OrderAssignment = new HashSet<OrderAssignment>();
        }
    
        public string InventaryNum { get; set; }
        public string Title { get; set; }
        public long Status { get; set; }
    
        public virtual EquipmentStatus EquipmentStatus { get; set; }
        public virtual ICollection<OrderAssignment> OrderAssignment { get; set; }
    }
}
