//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViPKS_PR10_FirstTry.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderAssignment
    {
        public long Id { get; set; }
        public long EmployeeId { get; set; }
        public string EquipmentInventaryNum { get; set; }
        public long ProductionOrderId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual ProductionOrder ProductionOrder { get; set; }
    }
}
