//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViPKS_PR10_FirstTry.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.ProductionOrder = new HashSet<ProductionOrder>();
        }
    
        public long Id { get; set; }
        public System.DateTime DateOfBegin { get; set; }
        public Nullable<System.DateTime> DateOfEnd { get; set; }
        public long OrderStatus { get; set; }
        public long ClientId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual OrderStatus OrderStatus1 { get; set; }
        public virtual ICollection<ProductionOrder> ProductionOrder { get; set; }
    }
}
