//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViPKS_PR10_FirstTry.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductionOrder = new HashSet<ProductionOrder>();
        }
    
        public long Articul { get; set; }
        public long SpecificationId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    
        public virtual Specification Specification { get; set; }
        public virtual ICollection<ProductionOrder> ProductionOrder { get; set; }
    }
}
