//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViPKS_PR10_FirstTry.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionOrder
    {
        public ProductionOrder()
        {
            this.OrderAssignment = new HashSet<OrderAssignment>();
        }
    
        public long Id { get; set; }
        public long OrderId { get; set; }
        public long ProductionArticul { get; set; }
        public float Quantity { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual ICollection<OrderAssignment> OrderAssignment { get; set; }
        public virtual Product Product { get; set; }
    }
}
