//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViPKS_PR10_FirstTry.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.SupplierPurchase = new HashSet<SupplierPurchase>();
        }
    
        public long Id { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<SupplierPurchase> SupplierPurchase { get; set; }
    }
}
